<?php

namespace proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class users extends \App\Entity\users implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\users' . "\0" . 'id', '' . "\0" . 'App\\Entity\\users' . "\0" . 'email', '' . "\0" . 'App\\Entity\\users' . "\0" . 'firstname', '' . "\0" . 'App\\Entity\\users' . "\0" . 'lastname', '' . "\0" . 'App\\Entity\\users' . "\0" . 'gender', '' . "\0" . 'App\\Entity\\users' . "\0" . 'zipcode', '' . "\0" . 'App\\Entity\\users' . "\0" . 'profile_image', '' . "\0" . 'App\\Entity\\users' . "\0" . 'address', '' . "\0" . 'App\\Entity\\users' . "\0" . 'is_active', '' . "\0" . 'App\\Entity\\users' . "\0" . 'latitude', '' . "\0" . 'App\\Entity\\users' . "\0" . 'longitude', '' . "\0" . 'App\\Entity\\users' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\users' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\users' . "\0" . 'deleted_at', '' . "\0" . 'App\\Entity\\users' . "\0" . 'events', '' . "\0" . 'App\\Entity\\users' . "\0" . 'forum', '' . "\0" . 'App\\Entity\\users' . "\0" . 'forumComments', '' . "\0" . 'App\\Entity\\users' . "\0" . 'videos', '' . "\0" . 'App\\Entity\\users' . "\0" . 'albums', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userProfile', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userActivities', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userWeapons', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userSpecies', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userProperties', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userRoles', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userNotes', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userFollowers', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userFollowed', '' . "\0" . 'App\\Entity\\users' . "\0" . 'notificationsForUser', '' . "\0" . 'App\\Entity\\users' . "\0" . 'notificationsAboutUser', '' . "\0" . 'App\\Entity\\users' . "\0" . 'city', '' . "\0" . 'App\\Entity\\users' . "\0" . 'country', '' . "\0" . 'App\\Entity\\users' . "\0" . 'state', 'password', 'rememberToken'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\users' . "\0" . 'id', '' . "\0" . 'App\\Entity\\users' . "\0" . 'email', '' . "\0" . 'App\\Entity\\users' . "\0" . 'firstname', '' . "\0" . 'App\\Entity\\users' . "\0" . 'lastname', '' . "\0" . 'App\\Entity\\users' . "\0" . 'gender', '' . "\0" . 'App\\Entity\\users' . "\0" . 'zipcode', '' . "\0" . 'App\\Entity\\users' . "\0" . 'profile_image', '' . "\0" . 'App\\Entity\\users' . "\0" . 'address', '' . "\0" . 'App\\Entity\\users' . "\0" . 'is_active', '' . "\0" . 'App\\Entity\\users' . "\0" . 'latitude', '' . "\0" . 'App\\Entity\\users' . "\0" . 'longitude', '' . "\0" . 'App\\Entity\\users' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\users' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\users' . "\0" . 'deleted_at', '' . "\0" . 'App\\Entity\\users' . "\0" . 'events', '' . "\0" . 'App\\Entity\\users' . "\0" . 'forum', '' . "\0" . 'App\\Entity\\users' . "\0" . 'forumComments', '' . "\0" . 'App\\Entity\\users' . "\0" . 'videos', '' . "\0" . 'App\\Entity\\users' . "\0" . 'albums', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userProfile', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userActivities', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userWeapons', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userSpecies', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userProperties', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userRoles', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userNotes', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userFollowers', '' . "\0" . 'App\\Entity\\users' . "\0" . 'userFollowed', '' . "\0" . 'App\\Entity\\users' . "\0" . 'notificationsForUser', '' . "\0" . 'App\\Entity\\users' . "\0" . 'notificationsAboutUser', '' . "\0" . 'App\\Entity\\users' . "\0" . 'city', '' . "\0" . 'App\\Entity\\users' . "\0" . 'country', '' . "\0" . 'App\\Entity\\users' . "\0" . 'state', 'password', 'rememberToken'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (users $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipcode', []);

        return parent::getZipcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipcode($zipcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipcode', [$zipcode]);

        return parent::setZipcode($zipcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileImage', []);

        return parent::getProfileImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileImage($profile_image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileImage', [$profile_image]);

        return parent::setProfileImage($profile_image);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($is_active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$is_active]);

        return parent::setIsActive($is_active);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationToken', []);

        return parent::getConfirmationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationToken($confirmation_token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationToken', [$confirmation_token]);

        return parent::setConfirmationToken($confirmation_token);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($created_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updated_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deleted_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deleted_at]);

        return parent::setDeletedAt($deleted_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvents', []);

        return parent::getEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvents($events)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvents', [$events]);

        return parent::setEvents($events);
    }

    /**
     * {@inheritDoc}
     */
    public function getForum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForum', []);

        return parent::getForum();
    }

    /**
     * {@inheritDoc}
     */
    public function setForum($forum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForum', [$forum]);

        return parent::setForum($forum);
    }

    /**
     * {@inheritDoc}
     */
    public function getForumComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForumComments', []);

        return parent::getForumComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setForumComments($forumComments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForumComments', [$forumComments]);

        return parent::setForumComments($forumComments);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideos', []);

        return parent::getVideos();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideos($videos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideos', [$videos]);

        return parent::setVideos($videos);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlbums()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlbums', []);

        return parent::getAlbums();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlbums($albums)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlbums', [$albums]);

        return parent::setAlbums($albums);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserProfile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserProfile', []);

        return parent::getUserProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserProfile($userProfile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserProfile', [$userProfile]);

        return parent::setUserProfile($userProfile);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserActivities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserActivities', []);

        return parent::getUserActivities();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserActivities($userActivities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserActivities', [$userActivities]);

        return parent::setUserActivities($userActivities);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserWeapons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserWeapons', []);

        return parent::getUserWeapons();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserWeapons($userWeapons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserWeapons', [$userWeapons]);

        return parent::setUserWeapons($userWeapons);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserSpecies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserSpecies', []);

        return parent::getUserSpecies();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserSpecies($userSpecies)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserSpecies', [$userSpecies]);

        return parent::setUserSpecies($userSpecies);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserProperties()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserProperties', []);

        return parent::getUserProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserProperties($userProperties)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserProperties', [$userProperties]);

        return parent::setUserProperties($userProperties);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserRoles', []);

        return parent::getUserRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserRoles($userRoles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserRoles', [$userRoles]);

        return parent::setUserRoles($userRoles);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserNotes', []);

        return parent::getUserNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserNotes($userNotes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserNotes', [$userNotes]);

        return parent::setUserNotes($userNotes);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserFollowers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserFollowers', []);

        return parent::getUserFollowers();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserFollowers($userFollowers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserFollowers', [$userFollowers]);

        return parent::setUserFollowers($userFollowers);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserFollowed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserFollowed', []);

        return parent::getUserFollowed();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserFollowed($userFollowed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserFollowed', [$userFollowed]);

        return parent::setUserFollowed($userFollowed);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthIdentifierName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthIdentifierName', []);

        return parent::getAuthIdentifierName();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthIdentifier', []);

        return parent::getAuthIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthPassword', []);

        return parent::getAuthPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRememberToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRememberToken', []);

        return parent::getRememberToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setRememberToken($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRememberToken', [$value]);

        return parent::setRememberToken($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRememberTokenName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRememberTokenName', []);

        return parent::getRememberTokenName();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailForPasswordReset()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailForPasswordReset', []);

        return parent::getEmailForPasswordReset();
    }

}
