<?php

namespace proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class notifications extends \App\Entity\notifications implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'id', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'is_read', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'forUsersNotification', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'aboutUsersNotification', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'notificationType'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'id', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'is_read', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'forUsersNotification', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'aboutUsersNotification', '' . "\0" . 'App\\Entity\\notifications' . "\0" . 'notificationType'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (notifications $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRead', []);

        return parent::getIsRead();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRead($is_read)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRead', [$is_read]);

        return parent::setIsRead($is_read);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($created_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getForUsersNotification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForUsersNotification', []);

        return parent::getForUsersNotification();
    }

    /**
     * {@inheritDoc}
     */
    public function setForUsersNotification($forUsersNotification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForUsersNotification', [$forUsersNotification]);

        return parent::setForUsersNotification($forUsersNotification);
    }

    /**
     * {@inheritDoc}
     */
    public function getAboutUsersNotification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAboutUsersNotification', []);

        return parent::getAboutUsersNotification();
    }

    /**
     * {@inheritDoc}
     */
    public function setAboutUsersNotification($aboutUsersNotification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAboutUsersNotification', [$aboutUsersNotification]);

        return parent::setAboutUsersNotification($aboutUsersNotification);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationType', []);

        return parent::getNotificationType();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationType($notificationType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationType', [$notificationType]);

        return parent::setNotificationType($notificationType);
    }

}
